<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #1a202c; background: #fff; }

        .header { background: #0A1628; color: #fff; padding: 24px 32px; }
        .header h1 { font-size: 22px; letter-spacing: 1px; }
        .header p { font-size: 11px; color: #00D4AA; margin-top: 4px; }

        .badge { display: inline-block; background: #00D4AA; color: #0A1628;
                 font-weight: bold; font-size: 10px; padding: 3px 10px;
                 border-radius: 20px; letter-spacing: 1px; }

        .body { padding: 32px; }

        .receipt-title { font-size: 17px; font-weight: bold; margin-bottom: 20px;
                         border-bottom: 2px solid #00D4AA; padding-bottom: 8px; }

        table.info { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        table.info td { padding: 7px 4px; vertical-align: top; }
        table.info td:first-child { color: #718096; width: 40%; }
        table.info td:last-child { font-weight: 600; }

        .amount-box { background: #f0fdf4; border: 1px solid #00D4AA;
                      border-radius: 8px; padding: 18px 24px; text-align: center;
                      margin-bottom: 24px; }
        .amount-box .label { font-size: 11px; color: #718096; text-transform: uppercase; }
        .amount-box .amount { font-size: 28px; font-weight: bold; color: #0A1628; }

        .footer { background: #f7fafc; border-top: 1px solid #e2e8f0;
                  padding: 16px 32px; font-size: 10px; color: #a0aec0;
                  text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>RENTALOS KENYA</h1>
        <p>Official Rent Payment Receipt</p>
    </div>

    <div class="body">
        <div class="receipt-title">
            Payment Receipt &nbsp;
            <span class="badge">{{ strtoupper($payment->status) }}</span>
        </div>

        <div class="amount-box">
            <div class="label">Amount Paid</div>
            <div class="amount">KSh {{ number_format($payment->amount, 2) }}</div>
        </div>

        <table class="info">
            <tr>
                <td>Receipt #</td>
                <td>{{ str_pad($payment->id, 6, '0', STR_PAD_LEFT) }}</td>
            </tr>
            <tr>
                <td>M-Pesa Reference</td>
                <td>{{ $payment->mpesa_reference ?? 'Pending' }}</td>
            </tr>
            <tr>
                <td>Payment Date</td>
                <td>{{ $payment->paid_at ? $payment->paid_at->format('d M Y, H:i') : '—' }}</td>
            </tr>
        </table>

        <table class="info">
            <tr>
                <td>Tenant</td>
                <td>{{ $payment->tenant->name }}<br><small>{{ $payment->tenant->phone }}</small></td>
            </tr>
            <tr>
                <td>Landlord</td>
                <td>{{ $payment->landlord->name }}</td>
            </tr>
            <tr>
                <td>Property</td>
                <td>{{ $payment->property->title }}<br><small>{{ $payment->property->county }}</small></td>
            </tr>
        </table>
    </div>

    <div class="footer">
        Generated by RentalOS Kenya &bull; {{ now()->format('d M Y H:i') }} &bull; This is a system-generated receipt.
    </div>
</body>
</html>
